name: 'Create Daily plan Issue'
description: 'automatic create daily plan issue for AnxGGYw/daily-plan'
inputs:
  token:
    description: 'github token'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
